# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abaf7564aa642c0426887cc1db974c68a34a26eac009fa9c9c0e044d7dcd0dded41ebb41694fc20acd3130ed8845a5bf85d7c8bbe420887c27f23c72db02f201

test:
  secret_key_base: cd9c98801bc4884c938c69e5707fddcefecca1fccef129c78b6a102c00009a7d40b223b12ec40d4b6ec20b52368fc7bd8a77bd8d06a3798d43fe230fa9378dc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
